concordia-fsae/firmware

.dockerignore
ENV_SETUP.md
buildroot.sh
components/steering_wheel/SConscript
docker-compose.yml
site_scons/site_tools/arm-none-eabi.py

isolated environment to build firmware code across os's

Docker env

---

components/aero_sensors/HW/HW_MPRL.c
components/aero_sensors/HW/include/HW_MPRL.h
components/aero_sensors/SConscript
components/aero_sensors/include/Files.h
components/aero_sensors/include/Sensors.h
components/aero_sensors/src/Files.c
components/aero_sensors/src/IO.c
components/aero_sensors/src/Sensors.c
components/aero_sensors/src/SystemManager.c
components/steering_wheel/SConscript
site_scons/site_tools/ars_decoder.py

Takes raw binary files from the ars module and converts into usable files with both raw and converted data which is then packaged

Adding ars file decoder

---

buildroot.sh
components/aero_sensors/FS/fatfs.c
components/aero_sensors/SConscript
components/aero_sensors/src/Files.c

-Minor fix small bug with spaces in buildroot
-Fix writing to Sd Card 
-Minor fix Files.c wrong FS_State_E in init

fix sd writing bug + additional setup fixes

---

components/bms_worker/src/CAN/CANIO-tx.c

… SWI probleSWI tramples RTOS currently, fix by not calling SWI to send messages although this needs to be fixed longterm

SWI CANTX fix for BMSW

---

.github/workflows/pull_request_template.md

1. Its in the name
1. Not applicable
1. Not applicable

Added pull request template

---

.github/workflows/reusable/build.yml
.github/workflows/reusable/clean_pull.yml

Added a clean pull which provides the SHA and SHA7 of the current branch Added a build target for any platform or targets
1. Abstract the sequences of workflows used and create reusable workflows
1. None
1. None. No hex diff

Added reusable workflows

---

.github/workflows/reusable/build.yml

1. Fix branch reference
1. None
1. None. No hex diff

Fix branch used in reusable workflows

---

.github/workflows/reusable/build.yml
.github/workflows/reusable/clean_pull.yml

Fix wording

---

.github/workflows/build.yml

1. Fix workflow reference
1. None

Re-reference clean pull workflow

---

.github/workflows/build.yml

Fix public workflows

---

.github/workflows/build.yml

Allow artifacts to be named to prevent upload collisions

---

.github/workflows/standard_checks.yml

1. Use reusable workflows in action
1. Checks will run with shared tests

Use reusable workflows in automated actions

---

.github/actions/build/action.yml
.github/actions/pull/action.yml
.github/workflows/build.yml
.github/workflows/standard_checks.yml

1. Adding reusable actions
1. Improves development ability of actions

Add actions and integrate into checks

---

.github/workflows/build.yml

1. Using reusable actions in master
1. No impact

Use public version of actions for cleanliness and stability

---

.github/actions/get-short-sha/action.yml

1. Fix workflow sha7 calculation
1. Correct workflows

Fix short-sha calculator

---

components/bms_boss/HW/drv_inputAD_componentSpecific.c
components/bms_boss/include/CANIO_componentSpecific.h
components/bms_boss/src/BMS.c
components/shared/code/DRV/drv_inputAD.c
components/shared/code/DRV/drv_inputAD.h
components/shared/code/DRV/drv_io.c
components/shared/code/DRV/drv_io.h
components/shared/code/DRV/drv_tps20xx.c
components/vc/front/src/HW/drv_inputAD_componentSpecific.c
components/vc/rear/src/HW/drv_inputAD_componentSpecific.c
network/definition/data/components/bmsb/bmsb-message.yaml
network/definition/data/components/bmsb/bmsb-signals.yaml

1. Bringup active state functionality of IO
2. Output BMSB input active states onto CAN
1. Changes functionality of input driver

Improve input driver

---

components/vc/front/include/HW/drv_inputAD_componentSpecific.h
components/vc/front/include/Module_componentSpecific.h
components/vc/front/src/HW/drv_inputAD_componentSpecific.c
components/vc/front/src/Module_componentSpecific.c
components/vc/pdu/include/HW/drv_inputAD_componentSpecific.h
components/vc/pdu/include/Module_componentSpecific.h
components/vc/pdu/src/HW/drv_inputAD_componentSpecific.c
components/vc/pdu/src/Module_componentSpecific.c
components/vc/rear/include/HW/drv_inputAD_componentSpecific.h
components/vc/rear/include/Module_componentSpecific.h
components/vc/rear/src/HW/drv_inputAD_componentSpecific.c
components/vc/rear/src/Module_componentSpecific.c

1. Cleans up the module manager for VCs
1. Corrects order of drivers and modules in VC

VC Module Manager cleanup

---

components/vc/rear/SConscript
components/vc/rear/include/CANIO_componentSpecific.h
components/vc/rear/include/brakeLight.h
components/vc/rear/src/Module_componentSpecific.c
components/vc/rear/src/brakeLight.c
network/definition/data/components/vcrear/vcrear-message.yaml
network/definition/data/components/vcrear/vcrear-rx.yaml
network/definition/data/components/vcrear/vcrear-signals.yaml
network/definition/discrete_values.yaml

1. Adds brake light module to vcrear
1. VCREAR now has control of the brake light

VCREAR Brake Light bringup

---

network/NetworkGen/NetworkGen.py
network/NetworkGen/templates/MessageUnpack_generated.h.mako
site_scons/site_tools/variants.py

1. Add ability to provide list of files in featuresels
2. Can retrieve CANRX function name from macro for pointer to function calls
3. Bugfix in YAMCAN RX, specified source buses on rx'd signals did not apply
1. No functional impacts to firmware
2. Infrastructure for YAMCAN improved
3. New feature for FeatureTree tool

Tracking continuous improvements cherry-picked from DEV branches

---

components/vc/front/src/HW/drv_pedalMonitor_componentSpecific.c

First pass APPS calibration on VCFRONT
1. Describe changes...
Tuned APPS in cage
change fault values
1. Describe impact...

First pass APPS calibration on VCFRONT

---

components/shared/code/DRV/drv_tps2hb16ab.c
components/shared/code/DRV/drv_tps2hb16ab.h
components/vc/pdu/SConscript
components/vc/pdu/include/Module_componentSpecific.h
components/vc/pdu/src/Module_componentSpecific.c
components/vc/pdu/src/cooling.c
components/vc/pdu/src/powerManager.c

1. Describe changes...
1. Describe impact...

Remove pump+fan from powerManager and integrate into dedicated cooling app on VCPDU

---

network/NetworkGen/NetworkGen.py
network/NetworkGen/classes/Types.py
network/definition/data/components/imu/imu-message.yaml
network/definition/data/components/imu/imu-rx.yaml
network/definition/data/components/imu/imu-signals.yaml
network/definition/data/components/imu/imu.yaml
network/definition/data/templates/signals.yaml

Add imu into yamcan
1. Higher VEH busload

imu: Initial yamcan implementation

---

components/bms_worker/src/Module.c
components/shared/code/RTOS/Module.c
components/shared/code/RTOS/Module.h
components/vc/front/include/CANIO_componentSpecific.h
components/vc/pdu/include/CANIO_componentSpecific.h
components/vc/rear/include/CANIO_componentSpecific.h

1. Add task iterations to shared code
2. Populate yamcan task iterations data
1. Increased CAN load

Add task iterations to RTOS Modules

---

components/vc/front/src/torque.c
components/vc/pdu/include/CANIO_componentSpecific.h
components/vc/pdu/include/powerManager.h
components/vc/pdu/src/cooling.c
components/vc/pdu/src/powerManager.c
network/definition/data/components/vcpdu/vcpdu-message.yaml

1. Fans only turn on in run mode
2. Added 5V rail current sense
1. GLV current now has all data
2. Cooling fan usage reduced

VCPDU current sense and cooling improvement

---

components/vc/rear/src/mcManager.c
network/NetworkGen/NetworkGen.py
network/definition/data/components/stw/stw-message.yaml
network/definition/data/components/stw/stw-signals.yaml
network/definition/data/components/udsClient/udsClient-message.yaml
network/definition/data/components/udsClient/udsClient-rx.yaml
network/definition/data/components/udsClient/udsClient.yaml
network/definition/data/components/vcrear/vcrear-rx.yaml
network/definition/discrete_values.yaml

1. Add current info to bridged messages on vcrear
2. Fix mcManager direction
3. Add gear to steering wheel can messages
4. Improve message reception and support uds across multiple buses on vcrear
1. Increased canbus load
2. Improved direction handling by vcrear
3. Bringup support on steering wheel to request reverse

Various improvements

---

uncrustify.cfg

1. Describe changes...
1. Describe impact...

misc: add uncrustify config

---

third_party/BUCK

.buck2: Fix third_party dependencies

---

drive-stack/can-bridge/BUCK
drive-stack/can-bridge/Cargo.toml
drive-stack/can-bridge/src/lib.rs
drive-stack/can-bridge/src/main.rs
third_party/BUCK
third_party/Cargo.lock
third_party/Cargo.toml
third_party/fixups/rustix/fixups.toml

1. Describe changes...
1. Describe impact...

can-bridge: Support message filtering and DBC decoding

---

components/vc/rear/src/mcManager.c

Currently there is significant torque shudder when no load conditions are present and the driver is not requesting torque. It is suspected that slack in the chain is causing control issues within the motor controller.
1. When in motion and torque is requested, add a minimumtorque request such that the car does not accelerate but keeps the chain loaded.

vcrear: Add minimum torque when car is in motion

---

.github/workflows/standard_checks.yml
components/bms_boss/BUCK
components/bms_worker/BUCK
components/bootloaders/STM/stm32f1/BUCK
components/steering_wheel/BUCK
components/vc/front/BUCK
components/vc/pdu/BUCK
components/vc/rear/BUCK
drive-stack/BUCK
drive-stack/can-bridge/BUCK
drive-stack/conUDS/BUCK
network/NetworkGen/NetworkGen.py
network/NetworkGen/classes/Can.py
toolchains/BUCK
toolchains/gcc/defs.bzl
toolchains/gcc/releases.bzl
tools/feature-tree/feature-tree.py

1. Workflow actions builds DBCs and archives all artifacts
1. N/A

github: Generate DBC in workflows. Archive artifacts from buck2 builds

---

.github/workflows/standard_checks.yml

Build buck2 firmware on macos runners

github: Run workflows on macos runners for firmware

---

components/steering_wheel/BUCK
embedded/platforms/stm32/f1/defs.bzl

fix stw build
stw build not broken

buck2: fix stw build

---

components/bms_boss/include/CANIO_componentSpecific.h
network/NetworkGen/NetworkGen.py
network/NetworkGen/classes/Can.py
network/NetworkGen/templates/MessageUnpack_generated.c.mako
network/NetworkGen/templates/NetworkDefines_generated.h.mako
network/NetworkGen/templates/message_pack.mako
network/definition/data/components/bmsb/bmsb-message.yaml
network/definition/data/components/bmsb/bmsb-signals.yaml
network/definition/data/components/bmsw/bmsw-message.yaml
network/definition/data/components/bmsw/bmsw-signals.yaml
network/definition/data/components/vcfront/vcfront-message.yaml
network/definition/data/components/vcpdu/vcpdu-message.yaml
network/definition/data/templates/signals.yaml
site_scons/site_tools/network.py

Add network and build crc infrastructure to start identifying mismatched firmware
Increased CAN load

Network + Build crc

---

components/bms_boss/BUCK
components/bms_worker/BUCK
components/vc/front/BUCK
components/vc/pdu/BUCK
components/vc/rear/BUCK
drive-stack/conUDS/defs.bzl
platforms/BUCK

Brings up batching functionality for uds deployable firmware

Buck2 support batch updates

---

drive-stack/conUDS/src/main.rs

1. Fix read DID in conUDS to output to stdout

conUDS: Output read DID result
