- docker-compose.yml
This is super important. Without this, changes to the container that correspond to changes in the firmware repo will make it so that older hashes of the firmware repo can't be built anymore.
> Pin container version

- embedded/platforms/stm32/f1/stm32f103xb.yaml
- embedded/platforms/stm32/f1/stm32f105.yaml
- network/NetworkGen/NetworkGen.py
1. Bugfix in yamcan calculation of busload. The issue was that messages from all buses were considered for a given node.
2. Removal of NUM_CAN_BUSES definition in chip config files
1. Corrects bus load calculation for each individual bus ore accurately
2. Changes build command of every file, but no compiler directive gated off this define flag
1. Not applicable
2. No hex diff, no test required
> Bug fix in bus load calculations and removal of compiler defines from command line

- components/bms_boss/HW/HW_can_componentSpecific.c
- components/bms_boss/SConscript
- components/bms_boss/src/UDS.c
- components/bms_worker/HW/HW_can_componentSpecific.c
- components/bms_worker/SConscript
- components/bms_worker/src/UDS.c
- components/bootloaders/STM/stm32f1/SConscript
- components/bootloaders/STM/stm32f1/src/CAN.c
- components/bootloaders/STM/stm32f1/src/UDS.c
- components/bootloaders/STM/stm32f1/src/main.c
- components/shared/code/HW/HW_can.c
- components/shared/code/app/CAN/CANIO-rx.c
- components/vc/front/SConscript
- components/vc/front/src/HW/HW_can_componentSpecific.c
- components/vc/front/src/UDS.c
- components/vc/pdu/SConscript
- components/vc/pdu/src/HW/HW_can_componentSpecific.c
- components/vc/pdu/src/UDS.c
- components/vc/rear/SConscript
- components/vc/rear/src/HW/HW_can_componentSpecific.c
- components/vc/rear/src/UDS.c
- embedded/libs/uds/include/lib_uds.h
- embedded/libs/uds/src/lib_udsServer.c
Issue is due to case-insensitivity of macOS (also impacts windows) leaking into linux docker container which does have a case-sensitive file system
> Fix file naming for docker on macOS

- buildroot.sh
- docker-compose.yml
Allow the user to select latest container instead of mainline container
> Add buildroot arguments

- .github/workflows/standard_checks.yml
- buildroot.sh
- docker-compose.yml
1. Buildroot script adds run commands to execute when the container starts
2. The script exits with the same error code as the container to be used in CI
3. Added a self-hosted workflow verification
1. Workflow codepaths are impacted
Run: https://github.com/concordia-fsae/firmware/actions/runs/13754667992/job/38460375031
> Improve buildroot.sh functionality

- .github/workflows/build.yml
- .github/workflows/standard_checks.yml
- components/bootloaders/SConscript
Build all bootloaders and vehicle controllers in seperate workflows to reduce time
Removed unecessary workflow dependencies. Can all run in parallel
1. Skip bootloaders in platform builds for standard workflow
2. Build all bootloaders in seperate workflow
3. Remove unnecessary workflow dependencies
1. Improved check runtimes
> Added ability to skip bootloaders in platform builds

- components/bms_boss/HW/HW_tim_componentSpecific.c
- components/bms_worker/HW/HW_Fans.c
- components/bms_worker/HW/HW_intc.c
- components/bms_worker/HW/HW_tim_componentSpecific.c
- components/bms_worker/HW/include/HW_tim_componentSpecific.h
- components/shared/code/HW/HW_tim.c
- components/shared/code/HW/HW_tim.h
Partial integration of BMSW
Support legacy BMSB
1. Improve the shared interface for setting PWM duty cycle
2. Integrate into bmsw
1. Impacts BMS fan control
> HW_tim improvement and BMSW set duty cycle integration

- components/shared/code/DRV/drv_tps20xx.c
- components/shared/code/DRV/drv_tps20xx.h
- components/vc/front/SConscript
- components/vc/front/include/HW/drv_outputAD_componentSpecific.h
- components/vc/front/src/HW/drv_outputAD_componentSpecific.c
- components/vc/front/src/HW/drv_tps20xx_componentSpecific.c
- components/vc/pdu/SConscript
- components/vc/pdu/include/HW/drv_outputAD_componentSpecific.h
- components/vc/pdu/src/HW/drv_outputAD_componentSpecific.c
- components/vc/rear/SConscript
- components/vc/rear/include/HW/drv_outputAD_componentSpecific.h
- components/vc/rear/src/HW/drv_outputAD_componentSpecific.c
- components/vc/rear/src/HW/drv_tps20xx_componentSpecific.c
1. Bringup output driver in VCs
1. TPS20XX driver now uses the output driver
> Bringup output driver in VCs

- components/shared/code/DRV/drv_pedalMonitor.c
- components/shared/code/DRV/drv_pedalMonitor.h
- components/vc/front/SConscript
- components/vc/front/include/CANIO_componentSpecific.h
- components/vc/front/include/HW/drv_pedalMonitor_componentSpecific.h
- components/vc/front/include/Module_componentSpecific.h
- components/vc/front/include/apps.h
- components/vc/front/include/bppc.h
- components/vc/front/include/torque.h
- components/vc/front/src/HW/drv_pedalMonitor_componentSpecific.c
- components/vc/front/src/Module_componentSpecific.c
- components/vc/front/src/apps.c
- components/vc/front/src/bppc.c
- components/vc/front/src/torque.c
- network/NetworkGen/NetworkGen.py
- network/definition/data/components/vcfront/vcfront-message.yaml
- network/definition/data/components/vcfront/vcfront-signals.yaml
- network/definition/data/templates/signals.yaml
- network/definition/discrete_values.yaml
1. Adds a pedal monitor which interpolates a sensed voltage into a pedal position
2. Pedal monitor has short to gnd and vbatt protection
3. Bringup APPS application on vcfront
4. Bringup BPPC application on vcfront
5. Bringup torque manager on vcfront
1. VCFRONT can use the front accelerator and brake pedal sensors
2. VCFRONT can specify a torque to request. Note the manager does not yet command the motor controller
> Bringup Pedal Monitor and APPS/BPPC

- components/shared/code/SharedApp_FeatureDefs.yaml
- components/shared/code/app/app_vehicleState.c
- components/shared/code/app/app_vehicleState.h
- components/vc/front/FeatureSels.yaml
- components/vc/front/SConscript
- components/vc/front/include/Module_componentSpecific.h
- components/vc/front/include/app_vehicleState_componentSpecific.h
- components/vc/front/src/Module_componentSpecific.c
- components/vc/pdu/FeatureSels.yaml
- components/vc/pdu/SConscript
- components/vc/pdu/include/CANIO_componentSpecific.h
- components/vc/pdu/include/HW/drv_inputAD_componentSpecific.h
- components/vc/pdu/include/Module_componentSpecific.h
- components/vc/pdu/include/app_vehicleState_componentSpecific.h
- components/vc/pdu/src/HW/drv_inputAD_componentSpecific.c
- components/vc/pdu/src/Module_componentSpecific.c
- network/definition/data/components/vcfront/vcfront-rx.yaml
- network/definition/data/components/vcpdu/vcpdu-message.yaml
- network/definition/data/components/vcpdu/vcpdu-rx.yaml
- network/definition/data/components/vcpdu/vcpdu-signals.yaml
- network/definition/discrete_values.yaml
1. Add vehicle power state shared application
2. Bringup leader follower architecture to vehicle state
3. All systems can utilize vehicle state for `ON_HV` and `TS_RUN` state progressions
4. VCPDU vehicle state leader. Handles power on and tracking vehicle state
5. VCFRONT is a vehicle state follower
1. Networked vehicle state progressio now tracked
2. No changes to current apps which gates any behaviours off of vehicle state
> Bringup vehicle state on VCPDU and VCFRONT

- components/vc/front/src/torque.c
1. Torque manager becomes active when the vehicle state is `TS_RUN`
1. Torque can now be requested by the vehicle. The MC manager has not been brought up so this will not drive the MC
> Integrate app_vehicleState into torque manager VCFRONT

- components/bms_boss/src/BMS.c
Changed logic for the bms boss contact cycling. 
Contacts will be cycled correctly, ensuring a high message before triggering the cycle.
> Changed logic for cycling contacts

- components/bootloaders/STM/stm32f1/variants.yaml
1. Fixed app_component_id: to the correct component in variants.yaml in /bootloaders
1. hwDesc->appComponentId == appDesc->appComponentId; line 60, of LIB_app.c returns true. Bootloader now runs.
- Run bootloader. This has been done.
> fixed variants.yaml bug

- network/NetworkGen/templates/dbc_functions.mako
1. Changes the bit position in the dbc when a signal has a big endianess
1. Properly read data from the can bus when big endian
> Fix endianess representation in dbc file

- components/bms_boss/HW/HW_adc_componentSpecific.c
- components/bms_boss/HW/drv_inputAD_componentSpecific.c
- components/shared/code/HW/HW_adc.c
- components/shared/code/HW/HW_adc.h
- components/stw_switch/src/HW/HW_adc_componentSpecific.c
- components/stw_switch/src/HW/drv_inputAD_componentSpecific.c
- components/vc/front/src/HW/HW_adc_componentSpecific.c
- components/vc/front/src/HW/drv_inputAD_componentSpecific.c
- components/vc/pdu/src/HW/HW_adc_componentSpecific.c
- components/vc/pdu/src/HW/drv_inputAD_componentSpecific.c
- components/vc/rear/src/HW/HW_adc_componentSpecific.c
- components/vc/rear/src/HW/drv_inputAD_componentSpecific.c
ADC unpacking was still driven by the DMA buffer. This caused an unnecessary unpacking of the buffer, as well as race conditions within the memory which could significantly impact the way that "simultaneous measurements" were taken by the firmware. This change improves the interface and allows the application to unpack the buffer if it wants to manually.
1. This will fix the "simultaneous" measurement read by the applications and ensure they are measured properly at the same time
2. Propogate all fixes to BMSB, SWS, VCFRONT, REAR, and PDU - This does not diff BMSW which will take some more figuring out with the 10kHz + normal codepath
> Fix ADC unpacking in VC

- components/vc/front/include/CANIO_componentSpecific.h
- components/vc/front/src/bppc.c
Allow feature brake pedal from pressure to drive pedal position
1. Gate the channel used for the brake pedal based upon the feature flag
1. Will allow the brake pedal output to be set by the brake pressure
> Fix brake pedal position output

- network/NetworkGen/classes/Can.py
1. Corrects ordering of CAN bus message cycle times for TX
1. Improvement
> Have the order of CAN message tables ascending based on cycle time

- components/shared/code/DRV/drv_tps20xx.c
- components/shared/code/DRV/drv_tps20xx.h
- components/vc/front/include/CANIO_componentSpecific.h
- components/vc/pdu/include/CANIO_componentSpecific.h
- components/vc/pdu/include/powerManager.h
- components/vc/pdu/src/powerManager.c
- components/vc/rear/include/CANIO_componentSpecific.h
- network/definition/data/components/vcfront/vcfront-message.yaml
- network/definition/data/components/vcfront/vcfront-signals.yaml
- network/definition/data/components/vcpdu/vcpdu-message.yaml
- network/definition/data/components/vcpdu/vcpdu-signals.yaml
- network/definition/data/components/vcrear/vcrear-message.yaml
- network/definition/data/components/vcrear/vcrear-signals.yaml
1. VCFRONT/REAR output their 5V hsd states onto CAN
1. No functional impact
> Add 5V HSD states onto CAN for VCFRONT/REAR

- components/vc/pdu/src/HW/drv_outputAD_componentSpecific.c
1. Currently the HSDs all auto-retry on a fault. This should not occur until the application is ready to reset
1. This will prevent the HSDs from auto-resetting
> Fix GPIO output config of VCPDU so HSD's dont auto-retry

- components/vc/front/SConscript
- components/vc/front/include/CANIO_componentSpecific.h
- components/vc/front/include/Module_componentSpecific.h
- components/vc/front/include/cockpitLights.h
- components/vc/front/src/Module_componentSpecific.c
- components/vc/front/src/cockpitLights.c
- network/definition/data/components/vcfront/vcfront-message.yaml
- network/definition/data/components/vcfront/vcfront-rx.yaml
- network/definition/data/components/vcfront/vcfront-signals.yaml
1. Bringup cockpit lights on vcfront
1. Dash lights will monitor the state of the BMS and IMD
> Cockpit Lights (related to #224)

- components/bms_boss/HW/HW_adc_componentSpecific.c
- components/bms_boss/HW/drv_inputAD_componentSpecific.c
- components/bms_boss/HW/include/HW_adc_componentSpecific.h
- components/bms_boss/HW/include/drv_inputAD_componentSpecific.h
- components/bms_boss/src/BMS.c
Utilized analog input to implement the voltage pack current sense for use in the precharge circuit.
Scales voltage appropriately and improves accuracy of precharge voltage readings.
> Bringup pack voltage sense

- components/vc/front/src/cockpitLights.c
1. BMS light will set when the BMS is faulted
1. Correct cockpitlight function
> Cockpit light set BMS light when BMS status is OFF

- components/vc/rear/src/mcManager.c
1. Default mcManager getDirectionCommand to reverse (forward on car)
1. Motor will now spin the wheels in the forward direction
> Default mcManager getDirectionCommand to reverse

- components/bms_worker/FeatureSels.yaml
- components/bms_worker/HW/drv_inputAD_componentSpecific.c
- components/bms_worker/include/BatteryMonitoring.h
- components/bms_worker/src/BatteryMonitoring.c
Remove blocking code from bmsw and add delay to the first cell measurement.
1. Adds delay before Cell 13 voltage measurement
2. Handles calibrating the bms chip asynchronously
3. Disable diagnostics
> BMSW Improvements

- components/bms_boss/BUCK
- components/bms_worker/BUCK
- components/bootloaders/STM/stm32f1/BUCK
- components/vc/front/BUCK
- components/vc/pdu/BUCK
- components/vc/rear/BUCK
- drive-stack/conUDS/defs.bzl
- network/BUCK
- network/NetworkGen/NetworkGen.py
- network/NetworkGen/defs.bzl
- network/definition/data/components/stw/stw-rx.yaml
- tools/uv/defs.bzl
conUDS now pulls the network manifest from yamcan
1. Better developer workflow
2. conUDS dynamically driven by yamcan
> Support network manifest generation and integrate into conUDS

- components/vc/pdu/include/CANIO_componentSpecific.h
- components/vc/pdu/include/powerManager.h
- components/vc/pdu/src/powerManager.c
- network/definition/data/components/vcpdu/vcpdu-message.yaml
- network/definition/data/components/vcpdu/vcpdu-signals.yaml
1. Implemented 5v pdu voltage sense.
2. Created the CAN signal.
1. Allows us to track 5v pdu voltage.
> added 5v pdu voltage sense and output over CAN

- components/bms_boss/BUCK
- components/bms_worker/BUCK
- components/bootloaders/STM/stm32f1/defs.bzl
- components/steering_wheel/BUCK
- components/vc/front/BUCK
- components/vc/pdu/BUCK
- components/vc/rear/BUCK
- embedded/openocd/BUCK
- embedded/openocd/defs.bzl
- embedded/openocd/releases.bzl
- toolchains/gcc/defs.bzl
- tools/defs.bzl
Adds support for debugging in buck2
> buck2: Bringup openocd support
